
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    /// <summary>
    /// 物品类型
    /// </summary>
    public enum EItemType
    {
        /// <summary>
        /// 武器
        /// </summary>
        Weapon = 0,
        /// <summary>
        /// 护甲
        /// </summary>
        Armor = 1,
        /// <summary>
        /// 消耗品
        /// </summary>
        Consumable = 2,
        /// <summary>
        /// 材料
        /// </summary>
        Material = 3,
    }

} 

