
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    /// <summary>
    /// 品质
    /// </summary>
    public enum EQuality
    {
        /// <summary>
        /// 白
        /// </summary>
        White = 0,
        /// <summary>
        /// 绿
        /// </summary>
        Green = 1,
        /// <summary>
        /// 蓝
        /// </summary>
        Blue = 2,
        /// <summary>
        /// 紫
        /// </summary>
        Purple = 3,
    }

} 

