
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Type = (EItemType)_buf.ReadInt();
        Quality = (EQuality)_buf.ReadInt();
        MaxStack = _buf.ReadInt();
        SellPrice = _buf.ReadInt();
    }

    public static Item DeserializeItem(ByteBuf _buf)
    {
        return new Item(_buf);
    }

    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly EItemType Type;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly EQuality Quality;
    /// <summary>
    /// 最大堆叠
    /// </summary>
    public readonly int MaxStack;
    /// <summary>
    /// 出售价格
    /// </summary>
    public readonly int SellPrice;
   
    public const int __ID__ = 2289459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "type:" + Type + ","
        + "quality:" + Quality + ","
        + "maxStack:" + MaxStack + ","
        + "sellPrice:" + SellPrice + ","
        + "}";
    }
}
}

